### ISSUE TITLE
Consider renaming this project

### ISSUE THREAD

**Issue by ggrossetie** [mermaid-js/docs#2]
I think the name is confusing as it only contains the Mermaid live editor (and not the documentation).

Maybe this project should be renamed to `live-editor-beta`?
We should also probably explain what is the difference with https://github.com/mermaid-js/mermaid-live-editor? Or maybe this project is outdated?

**Comment by sidharthv96** [comment]
Addressed in https://github.com/mermaid-js/docs/commit/468f1a9deb7a732b0d53d7d19665a31152fb5be2
